project:
  type: website
  output-dir: docs

website:
  title: "Teddy T W HLA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - presentations.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



